# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from Registration.server import stereo_vehicle_pb2 as stereo__vehicle__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stereo_vehicle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageProcessingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindHeight = channel.unary_unary(
                '/stereo_vehicle.ImageProcessing/FindHeight',
                request_serializer=stereo__vehicle__pb2.HeightRequest.SerializeToString,
                response_deserializer=stereo__vehicle__pb2.NumberResponse.FromString,
                _registered_method=True)
        self.IdentifyVehicle = channel.unary_unary(
                '/stereo_vehicle.ImageProcessing/IdentifyVehicle',
                request_serializer=stereo__vehicle__pb2.IdentifyVehicleRequest.SerializeToString,
                response_deserializer=stereo__vehicle__pb2.BooleanArrayResponse.FromString,
                _registered_method=True)
        self.ControlThread = channel.unary_unary(
                '/stereo_vehicle.ImageProcessing/ControlThread',
                request_serializer=stereo__vehicle__pb2.ControlRequest.SerializeToString,
                response_deserializer=stereo__vehicle__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.GetStabilizedFrame = channel.unary_unary(
                '/stereo_vehicle.ImageProcessing/GetStabilizedFrame',
                request_serializer=stereo__vehicle__pb2.Empty.SerializeToString,
                response_deserializer=stereo__vehicle__pb2.FrameResponse.FromString,
                _registered_method=True)


class ImageProcessingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindHeight(self, request, context):
        """Find the height of a pixel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IdentifyVehicle(self, request, context):
        """Identify vehicle in a video
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlThread(self, request, context):
        """Control the background task and optionally send a video
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStabilizedFrame(self, request, context):
        """Method to get the stabilized frame
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.FindHeight,
                    request_deserializer=stereo__vehicle__pb2.HeightRequest.FromString,
                    response_serializer=stereo__vehicle__pb2.NumberResponse.SerializeToString,
            ),
            'IdentifyVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.IdentifyVehicle,
                    request_deserializer=stereo__vehicle__pb2.IdentifyVehicleRequest.FromString,
                    response_serializer=stereo__vehicle__pb2.BooleanArrayResponse.SerializeToString,
            ),
            'ControlThread': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlThread,
                    request_deserializer=stereo__vehicle__pb2.ControlRequest.FromString,
                    response_serializer=stereo__vehicle__pb2.ControlResponse.SerializeToString,
            ),
            'GetStabilizedFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStabilizedFrame,
                    request_deserializer=stereo__vehicle__pb2.Empty.FromString,
                    response_serializer=stereo__vehicle__pb2.FrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stereo_vehicle.ImageProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stereo_vehicle.ImageProcessing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageProcessing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stereo_vehicle.ImageProcessing/FindHeight',
            stereo__vehicle__pb2.HeightRequest.SerializeToString,
            stereo__vehicle__pb2.NumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IdentifyVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stereo_vehicle.ImageProcessing/IdentifyVehicle',
            stereo__vehicle__pb2.IdentifyVehicleRequest.SerializeToString,
            stereo__vehicle__pb2.BooleanArrayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stereo_vehicle.ImageProcessing/ControlThread',
            stereo__vehicle__pb2.ControlRequest.SerializeToString,
            stereo__vehicle__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStabilizedFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stereo_vehicle.ImageProcessing/GetStabilizedFrame',
            stereo__vehicle__pb2.Empty.SerializeToString,
            stereo__vehicle__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
